### ISSUE TITLE
`media` at-rule with `min-width` condition, setting the html `font-size` increases the font-size on every recompute

### ISSUE THREAD

**Issue by kristofbolyai** [LadybirdBrowser/ladybird#1538] opened 2024-09-26 09:32 UTC
Hi,

This issue first appeared when testing Proton's main site (https://proton.me).

I've tracked down the issue and recreated a minimal reproducer: https://gist.github.com/kristofbolyai/9141da4b26b6bba6c5a762133299a5df

Expected behavior on (tested on Chromium) is the text size never changing.
Current behavior is text size changing on every style-recomputation (triggered by mouse-hover on the text, for example), effectively growing to an infinitely large size.

Chromium:
<img width="1624" alt="Screenshot 2024-09-26 at 11 24 44" src="https://github.com/user-attachments/assets/d4702ed3-0150-45f4-a3dc-bcde9fa74a20">

Ladybird (using an M1 Mac Pro + Appkit. The issue was also tested on Linux using Qt):
[Screen Recording 2024-09-26 at 11.24.55.webm](https://github.com/user-attachments/assets/ebb700aa-e981-446c-af8a-af1c7fb3e9ab)

I've done some basic digging in the Ladybird code, but admittedly, I didn't go too deep. 
If the issue is deemed valid, non-duplicate (couldn't find anything in GH-Issues related to this), I would be happy to try to work on this, given that the solution to the issue doesn't require bigger systematic changes (which I would prefer not to do as a first contribution).

Thank you for reading.

**Comment by AtkinsSJ** [comment] 2024-09-26 09:49
Hi! Thanks for the report.

I tried it out and the `@media` query isn't necessary, the same bug happens with:
```html
<html>
  <style>
    html {
    font-size: 1.0625rem
    }
  </style>

  Test Line
</html>
```

I'm closing this as a duplicate of #339. (`:root` and `html` are equivalent here.)

There was an attempt at solving this in #656 but that's gone untouched for months, so feel free to give it a go! You might get some ideas from looking at that.

**Closed by AtkinsSJ** 2024-09-26 09:49 UTC
