### ISSUE TITLE
Transparent accounting?

### ISSUE THREAD

**Issue by Kreyren** [LadybirdBrowser/ladybird#820] opened 2024-07-25 00:30 UTC
From your website i got the impression that you want to have a non-profit structure that is funded by the community to remain independent -> Make a transparent accounting so that it's easily verifiable and is a constant safeguard against this e.g. opencollective?

**Comment by awesomekling** [comment] 2024-07-25 06:04
The Ladybird Browser Initiative will publish its own financial reports at a regular interval, with maximum transparency.

Closing, as this is not a bug report :)

**Closed by awesomekling** 2024-07-25 06:04 UTC

**Comment by Kreyren** [comment] 2024-07-25 21:29
cool :+1:
