### ISSUE TITLE
Browser keep zooming while moving cursor on drawbu.dev

### ISSUE THREAD

**Issue by Sigmanificient** [LadybirdBrowser/ladybird#1766] opened 2024-10-13 08:55 UTC
I found this issue while going to a friend website that has been built using htmx.
The webview zoom only when moving the cursor:

![Peek 2024-10-13 10-49](https://github.com/user-attachments/assets/1ed790aa-762e-4f7c-99ea-7c827ca40496)

### Logs:

```
$ Ladybird
Ladybird PID file '/run/user/1003/Ladybird.pid' exists with PID 2874549, but process cannot be found
89395.360 WebContent(2874749): Unhandled JavaScript exception: [ReferenceError] 'XPathEvaluator' is not defined
89395.360 WebContent(2874749):     at https://unpkg.com/htmx.org@2.0.2/dist/htmx.min.js:1:49565
    at https://unpkg.com/htmx.org@2.0.2/dist/htmx.min.js:1:49565

89395.439 WebContent(2874749): Unhandled JavaScript exception: [TypeError] Cannot access property "version" on undefined object "htmx"
89395.439 WebContent(2874749):     at <unknown>

89395.797 WebContent(2874749): ResourceLoader: Failed load of: "https://drawbu.dev/favicon.ico", Error: Load failed: 404, Duration: 198ms
```

### Details

Linux distribution: NixOS, with Xorg
Ladybird: 0-unstable-2024-06-08 (commit `2f68e361370040d8cdc75a8ed8af4239134ae481`)

**Comment by AtkinsSJ** [comment] 2024-10-13 09:13
Thanks for the report! I can't check right now but this sounds like a duplicate of #339.

**Comment by shlyakpavel** [comment] 2024-12-15 15:01
It looks like this is still reproducible as of 108701c8997e8484890adee8dbf1d4cb81a51c39

**Comment by AtkinsSJ** [comment] 2024-12-18 12:24
Confirmed that it's the same issue as #339.

**Closed by AtkinsSJ** 2024-12-18 12:24 UTC
Labels: duplicate
