### ISSUE TITLE
Empty elements with border have whitespace between borders

### ISSUE THREAD

**Issue by avalanche-pwn** [LadybirdBrowser/ladybird#509] opened 2024-07-08 17:14 UTC
For example given:
```html
<!DOCTYPE html><div style="border: 5px solid red"></div>
```
In ladybird we get:
![image](https://github.com/LadybirdBrowser/ladybird/assets/46002716/d6f6291a-8ce6-42c1-b083-53851828f9c6)
and in firefox:
![image](https://github.com/LadybirdBrowser/ladybird/assets/46002716/e1a6acf3-c083-45b4-b178-3c131933d467)

**Comment by tcl3** [comment] 2024-07-08 20:07
Interestingly, I wasn't able to reproduce this issue until I changed the zoom level, which points to it possibly being some kind of rounding issue.

**Comment by AtkinsSJ** [comment] 2024-09-09 14:20
I think this is a duplicate of #245 (or closely related to it).

**Closed by AtkinsSJ** 2024-09-09 14:20 UTC
Labels: duplicate, layout
