### ISSUE TITLE
Arabic text in webpages rendered incorrectly

### ISSUE THREAD

**Issue by abdilra7eem** [LadybirdBrowser/ladybird#862] opened 2024-07-27 15:07 UTC
Arabic Text is rendered incorrectly in web pages, with the following issues:

1. The letters are rendered separated. They should be connected.
2. The text direction is rendered backwards (LTR instead of RTL).

The text is rendered correctly in the window title and tab title, but not the page itself.

Example:

Website Link: [Hsoub Academy website:](https://academy.hsoub.com/)

Screenshot from Ladybird:
![Screenshot from 2024-07-27 17-43-40](https://github.com/user-attachments/assets/1ed50fb8-3f2f-423d-a514-dfdd3cafa6b8)

Screenshot from another browser:
![Screenshot from 2024-07-27 18-00-05](https://github.com/user-attachments/assets/23493fef-0543-417f-8d50-7ec0cbb63ea4)

This issue affects not only Arabic, but all languages that use the Arabic writing system, including: Arabic, Farsi, Urdu, Kurdish, etc.

**Comment by shlyakpavel** [comment] 2024-12-16 13:15
<img width="1476" alt="image" src="https://github.com/user-attachments/assets/d5b3a5fe-45f3-4fc3-999c-b45a5f08d1cd" />
Apart from some minor layout issues, like buttons placed in a wrong order, looks fine to me as of e5436ce5935895e0d16be57261642f9313b94f15
If the issue is about the text, and not covers layout, I think it's fine to close it as resolved

**Closed** 2024-12-19 17:58 UTC
