### ISSUE TITLE
Build broken?

### ISSUE THREAD

**Issue by konrad1977** [LadybirdBrowser/ladybird#205] opened 2024-06-19 05:49 UTC
I tried to do a `rebuild` but I am not sure that is enough. I have upgraded my macOS version to Sonoma from Ventura. 
Is there a way to re-run `./configure` if any paths have changed?

I am not really sure If I am the problem (my environment) or if you guys broke something.

/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:119:42: error: reference to local binding 'x1' declared in enclosing lambda expression
                auto x = cubic_bezier_at(x1, x2, t);
                                         ^
/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:125:46: note: in instantiation of function template specialization 'Web::CSS::EasingStyleValue::Function::evaluate_at(double, bool)::(anonymous class)::operator()(const CubicBezier &)::(anonymous class)::operator()<double>' requested here
                cached_x_samples.append(solve(0.));
                                             ^
/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:76:26: note: 'x1' declared here
            auto const& [x1, y1, x2, y2, cached_x_samples] = bezier;
                         ^
/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:119:46: error: reference to local binding 'x2' declared in enclosing lambda expression
                auto x = cubic_bezier_at(x1, x2, t);
                                             ^
/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:76:34: note: 'x2' declared here
            auto const& [x1, y1, x2, y2, cached_x_samples] = bezier;
                                 ^
/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:120:42: error: reference to local binding 'y1' declared in enclosing lambda expression
                auto y = cubic_bezier_at(y1, y2, t);
                                         ^
/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:76:30: note: 'y1' declared here
            auto const& [x1, y1, x2, y2, cached_x_samples] = bezier;
                             ^
/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:120:46: error: reference to local binding 'y2' declared in enclosing lambda expression
                auto y = cubic_bezier_at(y1, y2, t);
                                             ^
/Users/mikaelkonradsson/Documents/git/Thirdparty/ladybird/Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp:76:38: note: 'y2' declared here
            auto const& [x1, y1, x2, y2, cached_x_samples] = bezier;

**Comment by BertalanD** [comment] 2024-06-19 10:42
Duplicate of #186.

There is an open PR with the fix: #203

**Closed by BertalanD** 2024-06-19 10:42 UTC

**Comment by BertalanD** [comment] 2024-06-19 10:47
update: we merged the PR, the issue should disappear if you pull again
